version: '3.3'

services:

  picontrolpanel:
    image: raspberry/picontrolpanel:prod
    container_name: raspberry_picontrolpanel
    build:
      context: ../.
      dockerfile: Docker/Dockerfile.pi64
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - '8081:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  portainer_data:
