version: '3.3'

services:

  picontrolpanel:
    image: rembert/pi-control-panel
    container_name: picontrolpanel
    environment:
      - TZ=America/Toronto
    ports:
      - '8081:8080'

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  portainer_data:
