version: '3.3'

services:

  picontrolpanel:
    image: rembert/pi-control-panel:dev
    container_name: picontrolpanel
    build:
      context: ../.
      dockerfile: Docker/Dockerfile.pi64
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - '8081:8080'
