version: '3.7'

services:

  picontrolpanel.api.graphql:
    build:
      dockerfile: Docker/Dockerfile
    environment:
      - TZ=America/Toronto
      - ASPNETCORE_ENVIRONMENT=Development

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  portainer_data: