name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
    paths: 
      - 'package/pi-control-panel_VERSION_ARCHITECTURE/DEBIAN/control'

jobs:
  release_version:
    name: Docker Build and Push (linux-arm)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Get package version
      id: get_debian_package_version
      shell: bash
      run: |
        echo "::set-output name=version::$(grep 'Version:' package/pi-control-panel_VERSION_ARCHITECTURE/DEBIAN/control | awk -F  ": " '{print $2}')"
    - name: QEMU Preparation
      shell: bash
      run: |
        apt-get update && apt-get install -y --no-install-recommends qemu-user-static binfmt-support
        update-binfmts --enable qemu-arm
        update-binfmts --display qemu-arm
        mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
        echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' > /proc/sys/fs/binfmt_misc/register
        cp -v /usr/bin/qemu-arm-static .
    - name: Docker Build and Push
      uses: docker/build-push-action@v1
      with:
        username: rembert
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: rembert/pi-control-panel
        path: src
        dockerfile: src/Docker/Dockerfile.pi
        tags: ${{ steps.get_debian_package_version.outputs.version }}-pi
