name: Pull Request Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/Api/PiControlPanel.Api.GraphQL/PiControlPanel.Api.GraphQL.csproj
    - name: Build
      run: dotnet build src/Api/PiControlPanel.Api.GraphQL/PiControlPanel.Api.GraphQL.csproj --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
