name: Release Debian Package

on:
  push:
    branches: [ master ]

jobs:
  dotnet_build:
    name: .NET Core
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build src/Api/PiControlPanel.Api.GraphQL/PiControlPanel.Api.GraphQL.csproj /p:DeployOnBuild=true /p:PublishProfile=RaspberryPi
    - name: Upload results for job debian_package
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: package

  debian_package:
    name: Debian package archive
    needs: [dotnet_build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download result from job dotnet_build
        uses: actions/download-artifact@v1
        with:
          name: package
      - shell: bash
        run: |
          cd package
          chmod +x pi-control-panel_VERSION.SUBVERSION_armhf/DEBIAN/p*
          dpkg-deb --build pi-control-panel_VERSION.SUBVERSION_armhf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: VERSION.SUBVERSION
          release_name: Release VERSION.SUBVERSION
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./package/pi-control-panel_VERSION.SUBVERSION_armhf.deb
          asset_name: pi-control-panel_VERSION.SUBVERSION_armhf.deb
          asset_content_type: application/vnd.debian.binary-package
